= MoHaeng API Docs
:doctype: book
:icons: font
// 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:source-highlighter: highlightjs
// toc (Table Of Contents)를 문서의 좌측에 두기
:toc: left
:toclevels: 2
:sectlinks:

[[Participant-API]]
== Participant API

[[Participant-역할-변경]]
=== - 다른 참여자 역할 변경

operation::change-participant's-role[snippets='http-request,path-parameters,request-headers,http-response']

==== - 요청 시 Header에 AccessToken이 없는 경우

operation::change-participant's-role(No Access Token)[snippets='http-response']

==== - 역할을 변경할 대상 참가자의 ID가 없는 경우

operation::change-participant's-role(Nonexistent Participant ID)[snippets='http-response']

==== - 변경하고자 하는 역할의 ID가 없는 경우

operation::change-participant's-role(Nonexistent ClubRole ID)[snippets='http-response']

==== - 일반 회원이 변경을 요청한 경우

operation::change-participant's-role(requester is general participant)[snippets='http-response']

==== - 바꾸려는 역할이 다른 모임의 역할인 경우

operation::change-participant's-role(change other club role)[snippets='http-response']

==== - 바꾸려는 회원이 다른 모임의 회원인 경우

operation::change-participant's-role(target is other club)[snippets='http-response']

==== - 회장으로 변경하려는 경우

operation::change-participant's-role(change to president role)[snippets='http-response']

==== - 자신과 계급이 동일하거나, 자신보다 높은 계급의 회원의 역할을 변경하려는 경우

operation::change-participant's-role(target is same rank or higher rank than requester)[snippets='http-response']
