= MoHaeng API Docs
:doctype: book
:icons: font
// 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:source-highlighter: highlightjs
// toc (Table Of Contents)를 문서의 좌측에 두기
:toc: left
:toclevels: 2
:sectlinks:

[[Club-Role-API]]
== Club Role API

[[Club-Role-역할제거]]
=== - 역할 제거

operation::delete-club-role[snippets='http-request,path-parameters,request-headers,http-response']

==== - 요청 시 Header에 AccessToken이 없는 경우

operation::delete-club-role(No Access Token)[snippets='http-response']

==== - 해당 회원이 역할을 제거하려는 모임에 가입되어있지 않은 경우

operation::delete-club-role(Nonexistent Participant)[snippets='http-response']

==== - 제거하려는 역할이 존재하지 않는 경우

operation::delete-club-role(Nonexistent ClubRole)[snippets='http-response']

==== - 요청자가 회장 혹은 임원이 아닌 경우

operation::delete-club-role(requester does not president or officer)[snippets='http-response']

==== - 회장 역할을 제하려는 경우

operation::delete-club-role(when delete president role)[snippets='http-response']

==== - 해당 범주에 속하는 역할이 단 한개 뿐이어서 제거할 수 없는 경우

operation::delete-club-role(only one role belonging to that category, so cannot be removed)[snippets='http-response']