= MoHaeng API Docs
:doctype: book
:icons: font
// 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:source-highlighter: highlightjs
// toc (Table Of Contents)를 문서의 좌측에 두기
:toc: left
:toclevels: 2
:sectlinks:

*link:../index.html[메인화면으로 돌아가기]*

[[Notification-API]]
== Notification API

[[Notification-알림-조회]]
=== `알림 조회 기본 형식`

operation::notification/query/query by id/FillOutApplicationFormNotification[snippets='http-request,path-parameters,request-headers,http-response']

==== - 요청 시 Header에 AccessToken이 없는 경우

operation::notification/query/query by id/fail/no access token[snippets='http-response']

==== - 알림의 ID가 존재하지 않거나 회원 자신이 받은 알림이 아닌 경우

operation::notification/query/query by id/fail/not found notification[snippets='http-response']

[[Notification-알림-조회-종류별]]
===  알림 종류별 Type 이름

[width="100%"]
|===
|설명|Type
|가입 신청 수락/거절에 대한 알림|ApplicationProcessedNotification
|가입 요청 생성에 대한 알림|FillOutApplicationFormNotification
|관리자가 가입 신청을 수락한 것에 대한 알림|OfficerApproveApplicationNotification
|관리자가 가입 신청을 거절한 것에 대한 알림|OfficerRejectApplicationNotification
|모임에서 추방된 것에 대한 알림|ExpelParticipantNotification
|모임이 제거되어 해당 모임에 대한 가입 신청서가 제거된 것에 대한 알림|DeleteApplicationFormCauseByClubDeletedNotification
|모임이 제거되어 해당 모임에서 탈퇴된 것에 대한 알림|DeleteParticipantCauseByClubDeletedNotification
|참여자의 역할이 변경되었다는 것에 대한 알림|ParticipantClubRoleChangedNotification
|===

=== 가입 신청 수락/거절에 대한 알림

operation::notification/query/query by id/ApplicationProcessedNotification[snippets='http-response,response-fields']

=== 가입 요청 생성에 대한 알림

operation::notification/query/query by id/FillOutApplicationFormNotification[snippets='http-response,response-fields']

=== 관리자가 가입 신청을 수락한 것에 대한 알림

operation::notification/query/query by id/OfficerApproveApplicationNotification[snippets='http-response,response-fields']

=== 관리자가 가입 신청을 거절한 것에 대한 알림

operation::notification/query/query by id/OfficerRejectApplicationNotification[snippets='http-response,response-fields']

=== 모임에서 추방된 것에 대한 알림

operation::notification/query/query by id/ExpelParticipantNotification[snippets='http-response,response-fields']

=== 모임이 제거되어 해당 모임에 대한 가입 신청서가 제거된 것에 대한 알림

operation::notification/query/query by id/DeleteApplicationFormCauseByClubDeletedNotification[snippets='http-response,response-fields']

=== 모임이 제거되어 해당 모임의 참여자들에게 모임이 제거되었다는 것을 알리기 위한 알림

operation::notification/query/query by id/DeleteParticipantCauseByClubDeletedNotification[snippets='http-response,response-fields']

=== 참여자의 역할이 변경되었다는 것에 대한 알림

operation::notification/query/query by id/ParticipantClubRoleChangedNotification[snippets='http-response,response-fields']
