= MoHeang API Docs
:doctype: book
:icons: font
// 문서에 표기되는 코드들의 하이라이팅을 highlightjs를 사용
:source-highlighter: highlightjs
// toc (Table Of Contents)를 문서의 좌측에 두기
:toc: left
:toclevels: 2
:sectlinks:


[[Member-API]]
== Member API

[[Member-회원가입]]
=== Member 회원가입
operation::sign-up[snippets='http-request,request-body,request-fields,http-response']

==== 중복 아이디로 회원가입 시
operation::sign-up fail(duplicated username)[snippets='http-response']

==== 필드가 다 채워지지 않은 경우
operation::sign-up fail(request fields contains empty value)[snippets='http-response']



[[Authentication-API]]
== Authentication API

[[Authentication-로그인]]
=== 로그인
operation::login[snippets='http-request,request-body,request-fields,http-response']

=== 아이디 혹은 비밀번호가 일치하지 않아 로그인 실패 시
operation::login fail(username or password miss match)[snippets='http-response']

==== 필드가 다 채워지지 않은 경우
operation::login fail(request fields contains empty value)[snippets='http-response']



[[Club-API]]
== Club API

[[Club-모임생성]]
=== 모임생성
operation::create-club[snippets='http-request,request-body,request-fields,http-response']

=== 생성 요청 시 Header에 AccessToken이 없는 경우
operation::create-club fail(No Access Token)[snippets='http-response']

==== 필드가 다 채워지지 않은 경우
operation::create-club fail(request fields contains empty value)[snippets='http-response']

==== 인원을 0으로 설정한 경우(-> 최대 인원으로 설정)
operation::create-club(max people count is 0 then setting MAX)[snippets='request-body,http-response']
